package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.model.ApartmentInfo;
import com.tencent.wxcloudrun.model.ApartmentInfoExample;
import java.util.List;

public interface ApartmentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment_info
     *
     * @mbggenerated
     */
    int countByExample(ApartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment_info
     *
     * @mbggenerated
     */
    int insert(ApartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment_info
     *
     * @mbggenerated
     */
    int insertSelective(ApartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment_info
     *
     * @mbggenerated
     */
    List<ApartmentInfo> selectByExample(ApartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment_info
     *
     * @mbggenerated
     */
    ApartmentInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApartmentInfo record);
}