package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.model.BuildingInfo;
import java.util.List;

public interface BuildingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    int insert(BuildingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    BuildingInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    List<BuildingInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BuildingInfo record);
}