package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.model.BuildingInfo;
import com.tencent.wxcloudrun.model.BuildingInfoExample;
import java.util.List;

public interface BuildingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    int countByExample(BuildingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    int insert(BuildingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    int insertSelective(BuildingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    List<BuildingInfo> selectByExample(BuildingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    BuildingInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BuildingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table building_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BuildingInfo record);
}