package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.model.CommitteeInfo;
import com.tencent.wxcloudrun.model.CommitteeInfoExample;
import java.util.List;

public interface CommitteeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_info
     *
     * @mbggenerated
     */
    int countByExample(CommitteeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_info
     *
     * @mbggenerated
     */
    int insert(CommitteeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_info
     *
     * @mbggenerated
     */
    int insertSelective(CommitteeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_info
     *
     * @mbggenerated
     */
    List<CommitteeInfo> selectByExample(CommitteeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_info
     *
     * @mbggenerated
     */
    CommitteeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommitteeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table committee_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommitteeInfo record);
}