package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.model.CommunityInfo;
import com.tencent.wxcloudrun.model.CommunityInfoExample;
import java.util.List;

public interface CommunityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int countByExample(CommunityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int insert(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int insertSelective(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    List<CommunityInfo> selectByExample(CommunityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    CommunityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommunityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommunityInfo record);
}