package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.model.FloorInfo;
import java.util.List;

public interface FloorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_info
     *
     * @mbggenerated
     */
    int insert(FloorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_info
     *
     * @mbggenerated
     */
    FloorInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_info
     *
     * @mbggenerated
     */
    List<FloorInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FloorInfo record);
}