package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.model.GridInfo;
import java.util.List;

public interface GridInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    int insert(GridInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    GridInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    List<GridInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GridInfo record);
}