package com.tencent.wxcloudrun.dao;

import com.tencent.wxcloudrun.model.UnitInfo;
import com.tencent.wxcloudrun.model.UnitInfoExample;
import java.util.List;

public interface UnitInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_info
     *
     * @mbggenerated
     */
    int countByExample(UnitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_info
     *
     * @mbggenerated
     */
    int insert(UnitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_info
     *
     * @mbggenerated
     */
    int insertSelective(UnitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_info
     *
     * @mbggenerated
     */
    List<UnitInfo> selectByExample(UnitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_info
     *
     * @mbggenerated
     */
    UnitInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UnitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UnitInfo record);
}