package com.tencent.wxcloudrun.model;

public class ApartmentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartment_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartment_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartment_info.grid_id
     *
     * @mbggenerated
     */
    private Integer gridId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartment_info.grid_name
     *
     * @mbggenerated
     */
    private String gridName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartment_info.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartment_info.id
     *
     * @return the value of apartment_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartment_info.id
     *
     * @param id the value for apartment_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartment_info.name
     *
     * @return the value of apartment_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartment_info.name
     *
     * @param name the value for apartment_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartment_info.grid_id
     *
     * @return the value of apartment_info.grid_id
     *
     * @mbggenerated
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartment_info.grid_id
     *
     * @param gridId the value for apartment_info.grid_id
     *
     * @mbggenerated
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartment_info.grid_name
     *
     * @return the value of apartment_info.grid_name
     *
     * @mbggenerated
     */
    public String getGridName() {
        return gridName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartment_info.grid_name
     *
     * @param gridName the value for apartment_info.grid_name
     *
     * @mbggenerated
     */
    public void setGridName(String gridName) {
        this.gridName = gridName == null ? null : gridName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartment_info.type
     *
     * @return the value of apartment_info.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartment_info.type
     *
     * @param type the value for apartment_info.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}