package com.tencent.wxcloudrun.model;

public class FamilyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.floor_id
     *
     * @mbggenerated
     */
    private Integer floorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.id
     *
     * @return the value of family_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.id
     *
     * @param id the value for family_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.name
     *
     * @return the value of family_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.name
     *
     * @param name the value for family_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.floor_id
     *
     * @return the value of family_info.floor_id
     *
     * @mbggenerated
     */
    public Integer getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.floor_id
     *
     * @param floorId the value for family_info.floor_id
     *
     * @mbggenerated
     */
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }
}