package com.tencent.wxcloudrun.model;

public class FamilyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.person_count
     *
     * @mbggenerated
     */
    private Integer personCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.party_flag
     *
     * @mbggenerated
     */
    private String partyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.low_income_flag
     *
     * @mbggenerated
     */
    private String lowIncomeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.solitude_flag
     *
     * @mbggenerated
     */
    private String solitudeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.floor_id
     *
     * @mbggenerated
     */
    private Integer floorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.floor_name
     *
     * @mbggenerated
     */
    private String floorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.unit_id
     *
     * @mbggenerated
     */
    private Integer unitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.unit_name
     *
     * @mbggenerated
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.building_id
     *
     * @mbggenerated
     */
    private Integer buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.building_name
     *
     * @mbggenerated
     */
    private String buildingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.apartment_id
     *
     * @mbggenerated
     */
    private Integer apartmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.apartment_name
     *
     * @mbggenerated
     */
    private String apartmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.grid_id
     *
     * @mbggenerated
     */
    private Integer gridId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.grid_name
     *
     * @mbggenerated
     */
    private String gridName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.party_branch_id
     *
     * @mbggenerated
     */
    private Integer partyBranchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.party_branch_name
     *
     * @mbggenerated
     */
    private String partyBranchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.community_id
     *
     * @mbggenerated
     */
    private Integer communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.community_name
     *
     * @mbggenerated
     */
    private String communityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.committee_id
     *
     * @mbggenerated
     */
    private Integer committeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.committee_name
     *
     * @mbggenerated
     */
    private String committeeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.id
     *
     * @return the value of family_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.id
     *
     * @param id the value for family_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.name
     *
     * @return the value of family_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.name
     *
     * @param name the value for family_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.person_count
     *
     * @return the value of family_info.person_count
     *
     * @mbggenerated
     */
    public Integer getPersonCount() {
        return personCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.person_count
     *
     * @param personCount the value for family_info.person_count
     *
     * @mbggenerated
     */
    public void setPersonCount(Integer personCount) {
        this.personCount = personCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.party_flag
     *
     * @return the value of family_info.party_flag
     *
     * @mbggenerated
     */
    public String getPartyFlag() {
        return partyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.party_flag
     *
     * @param partyFlag the value for family_info.party_flag
     *
     * @mbggenerated
     */
    public void setPartyFlag(String partyFlag) {
        this.partyFlag = partyFlag == null ? null : partyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.low_income_flag
     *
     * @return the value of family_info.low_income_flag
     *
     * @mbggenerated
     */
    public String getLowIncomeFlag() {
        return lowIncomeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.low_income_flag
     *
     * @param lowIncomeFlag the value for family_info.low_income_flag
     *
     * @mbggenerated
     */
    public void setLowIncomeFlag(String lowIncomeFlag) {
        this.lowIncomeFlag = lowIncomeFlag == null ? null : lowIncomeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.solitude_flag
     *
     * @return the value of family_info.solitude_flag
     *
     * @mbggenerated
     */
    public String getSolitudeFlag() {
        return solitudeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.solitude_flag
     *
     * @param solitudeFlag the value for family_info.solitude_flag
     *
     * @mbggenerated
     */
    public void setSolitudeFlag(String solitudeFlag) {
        this.solitudeFlag = solitudeFlag == null ? null : solitudeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.floor_id
     *
     * @return the value of family_info.floor_id
     *
     * @mbggenerated
     */
    public Integer getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.floor_id
     *
     * @param floorId the value for family_info.floor_id
     *
     * @mbggenerated
     */
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.floor_name
     *
     * @return the value of family_info.floor_name
     *
     * @mbggenerated
     */
    public String getFloorName() {
        return floorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.floor_name
     *
     * @param floorName the value for family_info.floor_name
     *
     * @mbggenerated
     */
    public void setFloorName(String floorName) {
        this.floorName = floorName == null ? null : floorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.unit_id
     *
     * @return the value of family_info.unit_id
     *
     * @mbggenerated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.unit_id
     *
     * @param unitId the value for family_info.unit_id
     *
     * @mbggenerated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.unit_name
     *
     * @return the value of family_info.unit_name
     *
     * @mbggenerated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.unit_name
     *
     * @param unitName the value for family_info.unit_name
     *
     * @mbggenerated
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.building_id
     *
     * @return the value of family_info.building_id
     *
     * @mbggenerated
     */
    public Integer getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.building_id
     *
     * @param buildingId the value for family_info.building_id
     *
     * @mbggenerated
     */
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.building_name
     *
     * @return the value of family_info.building_name
     *
     * @mbggenerated
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.building_name
     *
     * @param buildingName the value for family_info.building_name
     *
     * @mbggenerated
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.apartment_id
     *
     * @return the value of family_info.apartment_id
     *
     * @mbggenerated
     */
    public Integer getApartmentId() {
        return apartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.apartment_id
     *
     * @param apartmentId the value for family_info.apartment_id
     *
     * @mbggenerated
     */
    public void setApartmentId(Integer apartmentId) {
        this.apartmentId = apartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.apartment_name
     *
     * @return the value of family_info.apartment_name
     *
     * @mbggenerated
     */
    public String getApartmentName() {
        return apartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.apartment_name
     *
     * @param apartmentName the value for family_info.apartment_name
     *
     * @mbggenerated
     */
    public void setApartmentName(String apartmentName) {
        this.apartmentName = apartmentName == null ? null : apartmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.grid_id
     *
     * @return the value of family_info.grid_id
     *
     * @mbggenerated
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.grid_id
     *
     * @param gridId the value for family_info.grid_id
     *
     * @mbggenerated
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.grid_name
     *
     * @return the value of family_info.grid_name
     *
     * @mbggenerated
     */
    public String getGridName() {
        return gridName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.grid_name
     *
     * @param gridName the value for family_info.grid_name
     *
     * @mbggenerated
     */
    public void setGridName(String gridName) {
        this.gridName = gridName == null ? null : gridName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.party_branch_id
     *
     * @return the value of family_info.party_branch_id
     *
     * @mbggenerated
     */
    public Integer getPartyBranchId() {
        return partyBranchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.party_branch_id
     *
     * @param partyBranchId the value for family_info.party_branch_id
     *
     * @mbggenerated
     */
    public void setPartyBranchId(Integer partyBranchId) {
        this.partyBranchId = partyBranchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.party_branch_name
     *
     * @return the value of family_info.party_branch_name
     *
     * @mbggenerated
     */
    public String getPartyBranchName() {
        return partyBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.party_branch_name
     *
     * @param partyBranchName the value for family_info.party_branch_name
     *
     * @mbggenerated
     */
    public void setPartyBranchName(String partyBranchName) {
        this.partyBranchName = partyBranchName == null ? null : partyBranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.community_id
     *
     * @return the value of family_info.community_id
     *
     * @mbggenerated
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.community_id
     *
     * @param communityId the value for family_info.community_id
     *
     * @mbggenerated
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.community_name
     *
     * @return the value of family_info.community_name
     *
     * @mbggenerated
     */
    public String getCommunityName() {
        return communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.community_name
     *
     * @param communityName the value for family_info.community_name
     *
     * @mbggenerated
     */
    public void setCommunityName(String communityName) {
        this.communityName = communityName == null ? null : communityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.committee_id
     *
     * @return the value of family_info.committee_id
     *
     * @mbggenerated
     */
    public Integer getCommitteeId() {
        return committeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.committee_id
     *
     * @param committeeId the value for family_info.committee_id
     *
     * @mbggenerated
     */
    public void setCommitteeId(Integer committeeId) {
        this.committeeId = committeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.committee_name
     *
     * @return the value of family_info.committee_name
     *
     * @mbggenerated
     */
    public String getCommitteeName() {
        return committeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.committee_name
     *
     * @param committeeName the value for family_info.committee_name
     *
     * @mbggenerated
     */
    public void setCommitteeName(String committeeName) {
        this.committeeName = committeeName == null ? null : committeeName.trim();
    }
}