package com.tencent.wxcloudrun.model;

public class FamilyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.family_name
     *
     * @mbggenerated
     */
    private String familyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.floor_id
     *
     * @mbggenerated
     */
    private Integer floorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.floor
     *
     * @mbggenerated
     */
    private Integer floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.building_id
     *
     * @mbggenerated
     */
    private Integer buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.building_name
     *
     * @mbggenerated
     */
    private String buildingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.building_detail
     *
     * @mbggenerated
     */
    private String buildingDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.grid_id
     *
     * @mbggenerated
     */
    private Integer gridId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_info.grid_name
     *
     * @mbggenerated
     */
    private String gridName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.id
     *
     * @return the value of family_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.id
     *
     * @param id the value for family_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.family_name
     *
     * @return the value of family_info.family_name
     *
     * @mbggenerated
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.family_name
     *
     * @param familyName the value for family_info.family_name
     *
     * @mbggenerated
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.floor_id
     *
     * @return the value of family_info.floor_id
     *
     * @mbggenerated
     */
    public Integer getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.floor_id
     *
     * @param floorId the value for family_info.floor_id
     *
     * @mbggenerated
     */
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.floor
     *
     * @return the value of family_info.floor
     *
     * @mbggenerated
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.floor
     *
     * @param floor the value for family_info.floor
     *
     * @mbggenerated
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.building_id
     *
     * @return the value of family_info.building_id
     *
     * @mbggenerated
     */
    public Integer getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.building_id
     *
     * @param buildingId the value for family_info.building_id
     *
     * @mbggenerated
     */
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.building_name
     *
     * @return the value of family_info.building_name
     *
     * @mbggenerated
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.building_name
     *
     * @param buildingName the value for family_info.building_name
     *
     * @mbggenerated
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.building_detail
     *
     * @return the value of family_info.building_detail
     *
     * @mbggenerated
     */
    public String getBuildingDetail() {
        return buildingDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.building_detail
     *
     * @param buildingDetail the value for family_info.building_detail
     *
     * @mbggenerated
     */
    public void setBuildingDetail(String buildingDetail) {
        this.buildingDetail = buildingDetail == null ? null : buildingDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.grid_id
     *
     * @return the value of family_info.grid_id
     *
     * @mbggenerated
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.grid_id
     *
     * @param gridId the value for family_info.grid_id
     *
     * @mbggenerated
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_info.grid_name
     *
     * @return the value of family_info.grid_name
     *
     * @mbggenerated
     */
    public String getGridName() {
        return gridName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_info.grid_name
     *
     * @param gridName the value for family_info.grid_name
     *
     * @mbggenerated
     */
    public void setGridName(String gridName) {
        this.gridName = gridName == null ? null : gridName.trim();
    }
}