package com.tencent.wxcloudrun.model;

public class FloorInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_info.unit_id
     *
     * @mbggenerated
     */
    private Integer unitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_info.id
     *
     * @return the value of floor_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_info.id
     *
     * @param id the value for floor_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_info.name
     *
     * @return the value of floor_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_info.name
     *
     * @param name the value for floor_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_info.unit_id
     *
     * @return the value of floor_info.unit_id
     *
     * @mbggenerated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_info.unit_id
     *
     * @param unitId the value for floor_info.unit_id
     *
     * @mbggenerated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
}