package com.tencent.wxcloudrun.model;

import java.util.ArrayList;
import java.util.List;

public class GridInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public GridInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGridNameIsNull() {
            addCriterion("grid_name is null");
            return (Criteria) this;
        }

        public Criteria andGridNameIsNotNull() {
            addCriterion("grid_name is not null");
            return (Criteria) this;
        }

        public Criteria andGridNameEqualTo(String value) {
            addCriterion("grid_name =", value, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameNotEqualTo(String value) {
            addCriterion("grid_name <>", value, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameGreaterThan(String value) {
            addCriterion("grid_name >", value, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameGreaterThanOrEqualTo(String value) {
            addCriterion("grid_name >=", value, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameLessThan(String value) {
            addCriterion("grid_name <", value, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameLessThanOrEqualTo(String value) {
            addCriterion("grid_name <=", value, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameLike(String value) {
            addCriterion("grid_name like", value, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameNotLike(String value) {
            addCriterion("grid_name not like", value, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameIn(List<String> values) {
            addCriterion("grid_name in", values, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameNotIn(List<String> values) {
            addCriterion("grid_name not in", values, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameBetween(String value1, String value2) {
            addCriterion("grid_name between", value1, value2, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridNameNotBetween(String value1, String value2) {
            addCriterion("grid_name not between", value1, value2, "gridName");
            return (Criteria) this;
        }

        public Criteria andGridManagerIsNull() {
            addCriterion("grid_manager is null");
            return (Criteria) this;
        }

        public Criteria andGridManagerIsNotNull() {
            addCriterion("grid_manager is not null");
            return (Criteria) this;
        }

        public Criteria andGridManagerEqualTo(String value) {
            addCriterion("grid_manager =", value, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerNotEqualTo(String value) {
            addCriterion("grid_manager <>", value, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerGreaterThan(String value) {
            addCriterion("grid_manager >", value, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerGreaterThanOrEqualTo(String value) {
            addCriterion("grid_manager >=", value, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerLessThan(String value) {
            addCriterion("grid_manager <", value, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerLessThanOrEqualTo(String value) {
            addCriterion("grid_manager <=", value, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerLike(String value) {
            addCriterion("grid_manager like", value, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerNotLike(String value) {
            addCriterion("grid_manager not like", value, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerIn(List<String> values) {
            addCriterion("grid_manager in", values, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerNotIn(List<String> values) {
            addCriterion("grid_manager not in", values, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerBetween(String value1, String value2) {
            addCriterion("grid_manager between", value1, value2, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerNotBetween(String value1, String value2) {
            addCriterion("grid_manager not between", value1, value2, "gridManager");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdIsNull() {
            addCriterion("grid_manager_id is null");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdIsNotNull() {
            addCriterion("grid_manager_id is not null");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdEqualTo(Integer value) {
            addCriterion("grid_manager_id =", value, "gridManagerId");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdNotEqualTo(Integer value) {
            addCriterion("grid_manager_id <>", value, "gridManagerId");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdGreaterThan(Integer value) {
            addCriterion("grid_manager_id >", value, "gridManagerId");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("grid_manager_id >=", value, "gridManagerId");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdLessThan(Integer value) {
            addCriterion("grid_manager_id <", value, "gridManagerId");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdLessThanOrEqualTo(Integer value) {
            addCriterion("grid_manager_id <=", value, "gridManagerId");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdIn(List<Integer> values) {
            addCriterion("grid_manager_id in", values, "gridManagerId");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdNotIn(List<Integer> values) {
            addCriterion("grid_manager_id not in", values, "gridManagerId");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdBetween(Integer value1, Integer value2) {
            addCriterion("grid_manager_id between", value1, value2, "gridManagerId");
            return (Criteria) this;
        }

        public Criteria andGridManagerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("grid_manager_id not between", value1, value2, "gridManagerId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grid_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grid_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}