package com.tencent.wxcloudrun.model;

public class GridInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_info.grid_manager
     *
     * @mbggenerated
     */
    private String gridManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_info.grid_manager_id
     *
     * @mbggenerated
     */
    private Integer gridManagerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_info.party_branch_id
     *
     * @mbggenerated
     */
    private Integer partyBranchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_info.id
     *
     * @return the value of grid_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_info.id
     *
     * @param id the value for grid_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_info.name
     *
     * @return the value of grid_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_info.name
     *
     * @param name the value for grid_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_info.grid_manager
     *
     * @return the value of grid_info.grid_manager
     *
     * @mbggenerated
     */
    public String getGridManager() {
        return gridManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_info.grid_manager
     *
     * @param gridManager the value for grid_info.grid_manager
     *
     * @mbggenerated
     */
    public void setGridManager(String gridManager) {
        this.gridManager = gridManager == null ? null : gridManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_info.grid_manager_id
     *
     * @return the value of grid_info.grid_manager_id
     *
     * @mbggenerated
     */
    public Integer getGridManagerId() {
        return gridManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_info.grid_manager_id
     *
     * @param gridManagerId the value for grid_info.grid_manager_id
     *
     * @mbggenerated
     */
    public void setGridManagerId(Integer gridManagerId) {
        this.gridManagerId = gridManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_info.party_branch_id
     *
     * @return the value of grid_info.party_branch_id
     *
     * @mbggenerated
     */
    public Integer getPartyBranchId() {
        return partyBranchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_info.party_branch_id
     *
     * @param partyBranchId the value for grid_info.party_branch_id
     *
     * @mbggenerated
     */
    public void setPartyBranchId(Integer partyBranchId) {
        this.partyBranchId = partyBranchId;
    }
}