package com.tencent.wxcloudrun.model;

public class GridInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_info.grid_name
     *
     * @mbggenerated
     */
    private String gridName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_info.grid_manager
     *
     * @mbggenerated
     */
    private String gridManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grid_info.grid_manager_id
     *
     * @mbggenerated
     */
    private Integer gridManagerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_info.id
     *
     * @return the value of grid_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_info.id
     *
     * @param id the value for grid_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_info.grid_name
     *
     * @return the value of grid_info.grid_name
     *
     * @mbggenerated
     */
    public String getGridName() {
        return gridName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_info.grid_name
     *
     * @param gridName the value for grid_info.grid_name
     *
     * @mbggenerated
     */
    public void setGridName(String gridName) {
        this.gridName = gridName == null ? null : gridName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_info.grid_manager
     *
     * @return the value of grid_info.grid_manager
     *
     * @mbggenerated
     */
    public String getGridManager() {
        return gridManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_info.grid_manager
     *
     * @param gridManager the value for grid_info.grid_manager
     *
     * @mbggenerated
     */
    public void setGridManager(String gridManager) {
        this.gridManager = gridManager == null ? null : gridManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grid_info.grid_manager_id
     *
     * @return the value of grid_info.grid_manager_id
     *
     * @mbggenerated
     */
    public Integer getGridManagerId() {
        return gridManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grid_info.grid_manager_id
     *
     * @param gridManagerId the value for grid_info.grid_manager_id
     *
     * @mbggenerated
     */
    public void setGridManagerId(Integer gridManagerId) {
        this.gridManagerId = gridManagerId;
    }
}