package com.tencent.wxcloudrun.model;

public class MemberInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.name_index
     *
     * @mbggenerated
     */
    private String nameIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.party_member
     *
     * @mbggenerated
     */
    private String partyMember;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.grid_manager
     *
     * @mbggenerated
     */
    private String gridManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.special
     *
     * @mbggenerated
     */
    private String special;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.family_master
     *
     * @mbggenerated
     */
    private String familyMaster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.relationship_with_master
     *
     * @mbggenerated
     */
    private String relationshipWithMaster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.family_id
     *
     * @mbggenerated
     */
    private Integer familyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.family_name
     *
     * @mbggenerated
     */
    private String familyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.floor_id
     *
     * @mbggenerated
     */
    private Integer floorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.floor
     *
     * @mbggenerated
     */
    private Integer floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.building_id
     *
     * @mbggenerated
     */
    private Integer buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.building_name
     *
     * @mbggenerated
     */
    private String buildingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.building_detail
     *
     * @mbggenerated
     */
    private String buildingDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.grid_id
     *
     * @mbggenerated
     */
    private Integer gridId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.grid_name
     *
     * @mbggenerated
     */
    private String gridName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.id
     *
     * @return the value of member_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.id
     *
     * @param id the value for member_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.name
     *
     * @return the value of member_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.name
     *
     * @param name the value for member_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.name_index
     *
     * @return the value of member_info.name_index
     *
     * @mbggenerated
     */
    public String getNameIndex() {
        return nameIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.name_index
     *
     * @param nameIndex the value for member_info.name_index
     *
     * @mbggenerated
     */
    public void setNameIndex(String nameIndex) {
        this.nameIndex = nameIndex == null ? null : nameIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.sex
     *
     * @return the value of member_info.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.sex
     *
     * @param sex the value for member_info.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.age
     *
     * @return the value of member_info.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.age
     *
     * @param age the value for member_info.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.phone
     *
     * @return the value of member_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.phone
     *
     * @param phone the value for member_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.id_card
     *
     * @return the value of member_info.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.id_card
     *
     * @param idCard the value for member_info.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.party_member
     *
     * @return the value of member_info.party_member
     *
     * @mbggenerated
     */
    public String getPartyMember() {
        return partyMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.party_member
     *
     * @param partyMember the value for member_info.party_member
     *
     * @mbggenerated
     */
    public void setPartyMember(String partyMember) {
        this.partyMember = partyMember == null ? null : partyMember.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.grid_manager
     *
     * @return the value of member_info.grid_manager
     *
     * @mbggenerated
     */
    public String getGridManager() {
        return gridManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.grid_manager
     *
     * @param gridManager the value for member_info.grid_manager
     *
     * @mbggenerated
     */
    public void setGridManager(String gridManager) {
        this.gridManager = gridManager == null ? null : gridManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.special
     *
     * @return the value of member_info.special
     *
     * @mbggenerated
     */
    public String getSpecial() {
        return special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.special
     *
     * @param special the value for member_info.special
     *
     * @mbggenerated
     */
    public void setSpecial(String special) {
        this.special = special == null ? null : special.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.family_master
     *
     * @return the value of member_info.family_master
     *
     * @mbggenerated
     */
    public String getFamilyMaster() {
        return familyMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.family_master
     *
     * @param familyMaster the value for member_info.family_master
     *
     * @mbggenerated
     */
    public void setFamilyMaster(String familyMaster) {
        this.familyMaster = familyMaster == null ? null : familyMaster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.relationship_with_master
     *
     * @return the value of member_info.relationship_with_master
     *
     * @mbggenerated
     */
    public String getRelationshipWithMaster() {
        return relationshipWithMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.relationship_with_master
     *
     * @param relationshipWithMaster the value for member_info.relationship_with_master
     *
     * @mbggenerated
     */
    public void setRelationshipWithMaster(String relationshipWithMaster) {
        this.relationshipWithMaster = relationshipWithMaster == null ? null : relationshipWithMaster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.family_id
     *
     * @return the value of member_info.family_id
     *
     * @mbggenerated
     */
    public Integer getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.family_id
     *
     * @param familyId the value for member_info.family_id
     *
     * @mbggenerated
     */
    public void setFamilyId(Integer familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.family_name
     *
     * @return the value of member_info.family_name
     *
     * @mbggenerated
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.family_name
     *
     * @param familyName the value for member_info.family_name
     *
     * @mbggenerated
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName == null ? null : familyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.floor_id
     *
     * @return the value of member_info.floor_id
     *
     * @mbggenerated
     */
    public Integer getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.floor_id
     *
     * @param floorId the value for member_info.floor_id
     *
     * @mbggenerated
     */
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.floor
     *
     * @return the value of member_info.floor
     *
     * @mbggenerated
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.floor
     *
     * @param floor the value for member_info.floor
     *
     * @mbggenerated
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.building_id
     *
     * @return the value of member_info.building_id
     *
     * @mbggenerated
     */
    public Integer getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.building_id
     *
     * @param buildingId the value for member_info.building_id
     *
     * @mbggenerated
     */
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.building_name
     *
     * @return the value of member_info.building_name
     *
     * @mbggenerated
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.building_name
     *
     * @param buildingName the value for member_info.building_name
     *
     * @mbggenerated
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.building_detail
     *
     * @return the value of member_info.building_detail
     *
     * @mbggenerated
     */
    public String getBuildingDetail() {
        return buildingDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.building_detail
     *
     * @param buildingDetail the value for member_info.building_detail
     *
     * @mbggenerated
     */
    public void setBuildingDetail(String buildingDetail) {
        this.buildingDetail = buildingDetail == null ? null : buildingDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.grid_id
     *
     * @return the value of member_info.grid_id
     *
     * @mbggenerated
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.grid_id
     *
     * @param gridId the value for member_info.grid_id
     *
     * @mbggenerated
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.grid_name
     *
     * @return the value of member_info.grid_name
     *
     * @mbggenerated
     */
    public String getGridName() {
        return gridName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.grid_name
     *
     * @param gridName the value for member_info.grid_name
     *
     * @mbggenerated
     */
    public void setGridName(String gridName) {
        this.gridName = gridName == null ? null : gridName.trim();
    }
}