package com.tencent.wxcloudrun.model;

public class PartyBranchInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_branch_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_branch_info.community_id
     *
     * @mbggenerated
     */
    private Integer communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party_branch_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_branch_info.id
     *
     * @return the value of party_branch_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_branch_info.id
     *
     * @param id the value for party_branch_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_branch_info.community_id
     *
     * @return the value of party_branch_info.community_id
     *
     * @mbggenerated
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_branch_info.community_id
     *
     * @param communityId the value for party_branch_info.community_id
     *
     * @mbggenerated
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party_branch_info.name
     *
     * @return the value of party_branch_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party_branch_info.name
     *
     * @param name the value for party_branch_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}