package com.tencent.wxcloudrun.model;

public class UnitInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_info.building_id
     *
     * @mbggenerated
     */
    private Integer buildingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_info.id
     *
     * @return the value of unit_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_info.id
     *
     * @param id the value for unit_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_info.name
     *
     * @return the value of unit_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_info.name
     *
     * @param name the value for unit_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_info.building_id
     *
     * @return the value of unit_info.building_id
     *
     * @mbggenerated
     */
    public Integer getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_info.building_id
     *
     * @param buildingId the value for unit_info.building_id
     *
     * @mbggenerated
     */
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }
}