package com.tencent.wxcloudrun.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.committee_id
     *
     * @mbggenerated
     */
    private Integer committeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.committee_name
     *
     * @mbggenerated
     */
    private String committeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.community_id
     *
     * @mbggenerated
     */
    private Integer communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.community_name
     *
     * @mbggenerated
     */
    private String communityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.party_branch_id
     *
     * @mbggenerated
     */
    private Integer partyBranchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.party_branch_name
     *
     * @mbggenerated
     */
    private String partyBranchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.grid_id
     *
     * @mbggenerated
     */
    private Integer gridId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.grid_name
     *
     * @mbggenerated
     */
    private String gridName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone_number
     *
     * @return the value of user_info.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone_number
     *
     * @param phoneNumber the value for user_info.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.open_id
     *
     * @return the value of user_info.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.open_id
     *
     * @param openId the value for user_info.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.committee_id
     *
     * @return the value of user_info.committee_id
     *
     * @mbggenerated
     */
    public Integer getCommitteeId() {
        return committeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.committee_id
     *
     * @param committeeId the value for user_info.committee_id
     *
     * @mbggenerated
     */
    public void setCommitteeId(Integer committeeId) {
        this.committeeId = committeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.committee_name
     *
     * @return the value of user_info.committee_name
     *
     * @mbggenerated
     */
    public String getCommitteeName() {
        return committeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.committee_name
     *
     * @param committeeName the value for user_info.committee_name
     *
     * @mbggenerated
     */
    public void setCommitteeName(String committeeName) {
        this.committeeName = committeeName == null ? null : committeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.community_id
     *
     * @return the value of user_info.community_id
     *
     * @mbggenerated
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.community_id
     *
     * @param communityId the value for user_info.community_id
     *
     * @mbggenerated
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.community_name
     *
     * @return the value of user_info.community_name
     *
     * @mbggenerated
     */
    public String getCommunityName() {
        return communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.community_name
     *
     * @param communityName the value for user_info.community_name
     *
     * @mbggenerated
     */
    public void setCommunityName(String communityName) {
        this.communityName = communityName == null ? null : communityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.party_branch_id
     *
     * @return the value of user_info.party_branch_id
     *
     * @mbggenerated
     */
    public Integer getPartyBranchId() {
        return partyBranchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.party_branch_id
     *
     * @param partyBranchId the value for user_info.party_branch_id
     *
     * @mbggenerated
     */
    public void setPartyBranchId(Integer partyBranchId) {
        this.partyBranchId = partyBranchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.party_branch_name
     *
     * @return the value of user_info.party_branch_name
     *
     * @mbggenerated
     */
    public String getPartyBranchName() {
        return partyBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.party_branch_name
     *
     * @param partyBranchName the value for user_info.party_branch_name
     *
     * @mbggenerated
     */
    public void setPartyBranchName(String partyBranchName) {
        this.partyBranchName = partyBranchName == null ? null : partyBranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.grid_id
     *
     * @return the value of user_info.grid_id
     *
     * @mbggenerated
     */
    public Integer getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.grid_id
     *
     * @param gridId the value for user_info.grid_id
     *
     * @mbggenerated
     */
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.grid_name
     *
     * @return the value of user_info.grid_name
     *
     * @mbggenerated
     */
    public String getGridName() {
        return gridName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.grid_name
     *
     * @param gridName the value for user_info.grid_name
     *
     * @mbggenerated
     */
    public void setGridName(String gridName) {
        this.gridName = gridName == null ? null : gridName.trim();
    }
}